routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('register/{ref?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
 
Auth::routes(['verify' => true]); 
Route::get('/', 'HomeController@index')->name('home');

Route::get('/app/ask', 'HomeController@getAsk')->name('app.ask.get');
Route::post('/app/ask', 'HomeController@postAsk')->name('app.ask.post');
Route::get('/radio/list', 'HomeController@radio')->name('radio');


App\Http\Controllers\UserController::routes();
App\Http\Controllers\NoteController::routes();
App\Http\Controllers\NoteCommentController::routes();
App\Http\Controllers\UloginController::routes();
App\Http\Controllers\CheckUserDataController::routes();

//mission
App\Http\Controllers\Mission\MissionController::routes();

//group
App\Http\Controllers\GroupController::routes();

//complice
App\Http\Controllers\CompliceController::routes();

//accomplice
App\Http\Controllers\AccompliceController::routes();

//photo-report
App\Http\Controllers\PhotoReportController::routes();

//adavai
App\Http\Controllers\AdavaiController::routes();

//terminated
App\Http\Controllers\TerminatedController::routes();

//diary
App\Http\Controllers\DiaryController::routes();

//notification
App\Http\Controllers\NotificationController::routes();

//product
App\Http\Controllers\ProductController::routes();

//chat
App\Http\Controllers\ChatController::routes();
 
//private-chat
App\Http\Controllers\PrivateChatController::routes();

//admin
App\Http\Controllers\AdminController::routes();

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Date;
use App;
use App\NoteLike;
use App\User;
use App\Helpers\LocaleHelper;

class Note extends Model 
{
    /**
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [ 
        'owner_id',
        'author_id',
        'content',
        'type'    
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['posted_at'];

    /**
     * Relation to user
     *
     * @return relation
     */
    public function owner()
    {
        if ($this->type){
            return $this->belongsTo('App\Models\Group', 'owner_id', 'id');
        }
        return $this->belongsTo('App\User', 'owner_id', 'id');
    }

    /**
     * Relation to user
     *
     * @return relation
     */
    public function author()
    { 
        if($this->type == "group"){
            return $this->belongsTo('App\Models\Group', 'owner_id', 'id');
        } 
        else return $this->belongsTo('App\User', 'author_id', 'id');
    }

    /**
     * Relation to user
     *
     * @return relation
     */
    public function group()
    { 
        return $this->belongsTo('App\Models\Group', 'owner_id', 'id');
    }

    /**
     * Relation to Diary
     *
     * @return relation
     */
    public function diary()
    {
        return $this->belongsTo('App\Models\Diary', 'owner_id');
    }

    /**
     * Relation to note_image
     *
     * @return relation
     */
    public function images()
    {
        return $this->hasMany('App\NoteImage', 'note_id', 'id');
    }

   /**
     * Relation to note_files
     *
     * @return relation
     */
    public function files()
    {
        return $this->hasMany('App\Models\NoteFile', 'note_id', 'id');
    }

    public function adavai()
    {
        return $this->hasOne('App\Models\NoteAdavai', 'note_id', 'id');
    }

    /**
     * Relation to NoteParam
     *
     * @return relation
     */
    public function params()
    {
        return $this->hasOne('App\Models\NoteParam', 'note_id', 'id');
    }

    /**
     * Relation to note_comment
     *
     * @return relation
     */
    public function comments()
    {
        return $this->hasMany('App\NoteComment', 'note_id', 'id');
    }

    /**
     * Relation to NoteLike
     *
     * @return relation
     */
    public function likes()
    {
        return $this->hasMany('App\NoteLike', 'note_id', 'id');
    }

    /**
     * Relation to AdavaiSubsribers
     *
     * @return relation
     */
    public function adavaiki()
    {
        return $this->hasMany('App\Models\AdavaiSubscriber', 'note_id', 'id');
    }

    public function subscriptions()
    {
        return $this->hasMany('App\Models\AdavaiSubscriber', 'note_id', 'id');
    }
 
    /**
     * Relation to NoteLike
     *
     * @return relation
     */
    public function reposts()
    {
        //return $this->belongsTo('App\Models\Repost', 'id');
        return $this->hasMany('App\Models\Repost', 'note_id', 'id');
    }

	/**
     * Check if user can edit/delete
     *
     * @return boolean
     */
    public function canManage()
    {
        return ($this->author_id == Auth::user()->id || $this->owner_id == Auth::user()->id);
    }
 
    /** 
     * Get the administrator flag for the user.
     *
     * @return bool
     */
    public function getPostedAtAttribute() 
    { 
        Date::setlocale(App::getLocale());
        return Date::parse($this->attributes['created_at'])
                        ->setTimezone(LocaleHelper::userTimeZone())
                        ->format('j F Y H:i');
    }

    /**
     * Get comments count
     *
     * @return bool
     */
    public function getCommentsCountAttribute()
    {
        return $this->comments()->count();
    }

    /**
     * Get likes count
     *
     * @return bool
     */
    public function getLikesCountAttribute()
    {
        return $this->likes()->count();
    }


    public function getContentShortAttribute()
    {
        return substr($this->content, 0, 100);
    }

    public function getSubscriptionsCountAttribute()
    {
        return $this->subscriptions->count();
    }

    public function scopeWithMainRelations($query)
    {
        return $query->with(['author', 'images', 'owner', 'group', 'files', 'adavai.city', 'diary'])
                     ->with(['adavai' => function($q){
                                $q->withCount('notifications');
                            }])
                     ->withCount(['comments', 'likes', 'subscriptions']);
    }

    /**
     * Delete relation models
     *
     * @return bool
     */
    public static function boot() {
        parent::boot();

        self::deleting(function($item) {
            $item->images()->each(function($img) {
                $img->delete();
            });

            $item->files()->each(function($item) {
                $item->delete();
            });

            $item->likes()->each(function($like) {
                $like->delete();
            });
        });
    }

}

app/Http/Controllers/AdavaiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Models\Mission\MissionCategory;
use App\Country;
use App\Note;
use App\User;
use App\Models\Report;
use App\Models\AdavaiSubscriber;
use App\Models\Settings;
use App\Models\Award;
use App\Models\UserAdavaiProfile;
use App\Models\AdavaiLicensePurchase;
use App\Events\AdavaiCreated; 
use App\Events\UserJoinedToAdavai;
use App\Events\NotesFetched;
use App\Helpers\NoteHelper;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

class AdavaiController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */ 
    public function __construct()
    {
        $this->middleware(['auth', 'check.user.data', 'verified', 'last.seen']);
    }

    /**
     * Accomplice list
     *
     * @return redirect
     */
    public function list()
    {
        $activeAdavai = AdavaiSubscriber::getUserSubscribedNotes(Auth::user()->id, true, 3);
        $inactiveAdavai = AdavaiSubscriber::getUserSubscribedNotes(Auth::user()->id, false, 3);

        return view('site.adavai.list', [
            'activeAdavai' => $activeAdavai,
            'inactiveAdavai' => $inactiveAdavai,
        ]);
    }

    /**
     * Adavai profile
     *
     * @return redirect
     */
    public function profile($nickname = false)
    {
        $user = $nickname ? User::with('createdGroups')->where('nickname', $nickname)->firstOrFail() : Auth::user()->load('createdGroups');
        $categories = MissionCategory::all();
        $countries = Country::with('cities')->get(); 


        $user->adavaiProfile ?: $user->adavaiProfile()->create(['enable_notifications' => 1]);

        return view('site.adavai.profile', [
            'user' => $user,
            'own' => $user->id == Auth::user()->id,
            'categories' => $categories,
            'countries' => $countries,
        ]);
    }

    /**
     * Join
     *
     * @return redirect
     */
    public function join($id)
    {
        $note = Note::whereHas('adavai')->findOrFail($id);

        $join = Auth::user()->adavaiki()->where(['note_id' => $note->id])->first();
        $joined = false;

        if ($join) {
            $join->delete(); 
            event(new UserJoinedToAdavai($note, $joined, Auth::user()));
        } else {
            if ($note->adavai->check_limit) {
                Auth::user()->adavaiki()->create(['note_id' => $note->id]);
                $joined = true;
                event(new UserJoinedToAdavai($note, $joined, Auth::user()));
            } else {
                $joined = 'limit';
            }
        }

        return response()->json([
            'joined' => $joined
        ], 200);
    }

    public function create()
    {
        $categories = MissionCategory::all();
        $countries = Country::with('cities')->get(); 

        return view('site.adavai.create', [
            'categories' => $categories,
            'countries' => $countries,
        ]);
    }

    public function store(Request $request)
    {
        if (!Auth::user()->adavaiProfile->verified) {
            return redirect()->route('adavai.profile')->with([
                'message' => __('adavai.not_able_to_add'),
                'alert' => 'alert-danger'
            ]);
        }
        $request->validate([
            'city_id' => 'required',
            'category_id' => 'required',
            'limit' => 'required|integer|min:1',
            'date' => 'required',
            'content' => 'required',
        ]);

        $note = Note::create([
            'owner_id' => 0,
            'author_id' => Auth::user()->id,
            'content' => $request->content,
            'type' => 'adavai' 
        ]);

        $note->adavai()->create($request->only([
            'city_id',
            'category_id',
            'limit',
            'check_age',
            'date',
        ]));

        event(new AdavaiCreated($note));

        $note->reposts()->create(['user_id' => Auth::user()->id]);

        return redirect()->route('adavai.profile', [Auth::user()->nickname, 'note' => $note->id]);
    }

    public function getUserAdavaiNotes(Request $request)
    {
        $user = User::findOrFail($request->profile_id);

        $notes = $user->addedNotes()
                            ->whereHas('adavai')
                            ->where(['type' => 'adavai'])
                            ->get(['id']);
        
        $notes = Note::where(function($q) use ($request) {
                            $request->search ? $q->where('content', 'like', '%'.$request->search_input.'%') : null;
                        })
                        ->withMainRelations()
                        ->whereIn('id', $notes->pluck('id'))
                        ->orderBy('id', 'desc')
                        ->paginate(5);                            

        $notes = NoteHelper::userLikesAndAdavais($notes);
        event(new NotesFetched($notes));
        return response()->json([
            'notes' => $notes->values()->toArray()
        ], 200);
    }

    public function getAdavaiNotes(int $userNotes, Request $request)
    {
        $notes = Note::whereHas('adavai')
                        ->where(['type' => 'adavai'])
                        ->get(['id']);

        $notes = Note::where(function($q) use ($request) {
                            $request->search ? $q->where('content', 'like', '%'.$request->search_input.'%') : null;
                        })
                        ->withMainRelations()
                        ->whereIn('id', $notes->pluck('id'))
                        ->orderBy('id', 'desc')
                        ->paginate(5);  
        
        $notes = $this->adavaiSortDefault($notes);

        if ($userNotes) {
            $notes = $notes->filter(function($note){
                return $note->author_id == Auth::user()->id;
            });
        }

        $notes = NoteHelper::userLikesAndAdavais($notes);
        event(new NotesFetched($notes));
        return response()->json([
            'notes' => $notes->sortByDesc('order')->values()->toArray()
        ], 200);
    }

    private function adavaiSortDefault($notes)
    {
        return $notes->each(function($i){
            $i->order += $i->likes->count() ? $i->likes->count() / 100 : 0;
            $i->order += $i->subscriptions->count() ? $i->subscriptions->count() / 100 : 0;
            if (Auth::user()->city == $i->adavai->city_id) $i->order += 2;
            if ($i->author->adavaiProfile->active_license) $i->order += 1;
        });
    }

    public function report(int $id)
    {
        if (!Report::where(['type' => 'adavai', 'item_id' => $id])->first()) {
            Report::create([
                'item_id' => $id,
                'user_id' => Auth::user()->id,
                'type' => 'adavai',
                'report' => 1
            ]); 
        }

        $settings = Settings::first();
        $settings->report_count = $settings->report_count + 1;
        $settings->update();

        return response()->json([
            'success' => true
        ]);
    }

    public function edit(int $id)
    {
        $note = Auth::user()->addedNotes()->whereHas('adavai')->findOrFail($id);
        $countries = Country::with('cities')->get();
        $categories = MissionCategory::all();

        return view('site.adavai.edit', [
            'note' => $note,
            'countries' => $countries,
            'categories' => $categories,
        ]);
    }

    public function update(int $id, Request $request)
    {
        $note = Auth::user()->addedNotes()->whereHas('adavai')->findOrFail($id);
        if (!$note->adavai->editable_adavai) {

            return redirect()->route('adavai.edit', $note->id)->with([
                'message' => __('adavai.not_editable'),
                'alert' => 'alert-danger'
            ]);
        }

        $note->update($request->only(['content']));
        $note->adavai()->update($request->only([
            'category_id',
            'city_id',
            'date',
            'limit',
            'check_age',
        ]));

        return redirect()->back();  
    }

    public function leave(int $id)
    {
        $note = Note::findOrFail($id);
        $subscription = Auth::user()->adavaiki()->where(['note_id' => $note->id])->firstOrFail();
        $subscription ? $subscription->delete() : null;
        event(new UserJoinedToAdavai($note, false, Auth::user()));

        return redirect()->back(); 
    }

    public function profileSettings()
    {
        $user = Auth::user();
        $user->adavaiProfile ?: $user->adavaiProfile()->create();

        return view('site.adavai.settings', [
            'user' => $user,
        ]);
    }

    public function profileSettingsUpdate(Request $request)
    {
        $user = Auth::user();
        $request->validate([
            'passport' => 'file|mimes:jpeg,jpg,png,JPEG',
        ]);

        if ($request->passport) {
            $passport = md5(time()).'.'.$request->passport->getClientOriginalExtension();
            Storage::disk('site')->put('img/users/passports/'.$passport, File::get($request->passport));
            $user->adavaiProfile->deletePassportImg();
        } else {
            $passport = $user->adavaiProfile->passport;
        }

        $user->adavaiProfile()->update([
            'full_address' => $request->address,
            'passport' => $passport ?? null,
            'enable_notifications' => $request->enable_notifications ?? 0,
            'auto_prolong' => $request->auto_prolong ?? 0,
        ]);

        return redirect()->back()->with([
            'alert' => 'alert-success',
            'message' => __('message.adavai.profile.update'),
        ]);
    }

    public function subscribers(int $noteId)
    {
        $note = Note::whereHas('adavai')->findOrFail($noteId);
        

resources/views/site/adavai/create.blade.php
@extends('layouts.main')

@section('title')
	{{ __('adavai.add.fancy') }}
@endsection
<!--@todo translate-->
@section('content') 

		  <div class="col-md-8 px-5 py-1 profile-block">
		  	
		  	<h4 class="page-top-title my-3">{{ __('adavai.add.fancy') }}</h4>

		  	@include('common.alerts')
		  	@include('common.errors')
		  	
		  	<div class="col-12 block-white px-md-5 px-3 py-4 text-left">
		  		<div class="col-md-8 col-12">
			  		<form action="{{ route('adavai.store') }}" class="table-form" method="post">
			  			@csrf
			  		<table class="table table-sm table-borderless">
						<tr>
							<td class="table-form-label">{{ __('adavai.subject') }}:</td>
							<td class="form-group">
						        <select class="form-control" name="category_id" required>
									@if($categories->count() > 0)
										@foreach($categories as $cat)
											<option value="{{ $cat->id }}">{{ $cat->title }}</option>
										@endforeach
									@endif
								</select>
							</td>
						</tr>
						<tr>
							<td class="table-form-label">{{ __('adavai.city') }}:</td>
							<td  class="form-group">
						        <select class="form-control" name="city_id">
									@if($countries->count() > 0)
										@foreach($countries as $country)
										<optgroup label="{{ $country->title }}"></optgroup>
											@if($country->cities->count() > 0)
												@foreach($country->cities as $city)
													<option value="{{ $city->id }}">{{ $city->title }}</option>
												@endforeach
											@endif
										@endforeach
									@endif
								</select>
							</td>
						</tr>
						<tr>
							<td class="table-form-label">{{ __('adavai.date') }}:</td>
							<td  class="form-group">
								<input type="datetime-local" name="date" class="form-control" value="{{ old('date') }}" required>
							</td>
						</tr>
						<tr>
							<td class="table-form-label">{{ __('adavai.participants.amount') }}:</td>
							<td  class="form-group">
								<input type="number" name="limit" class="form-control" min="1" value="{{ old('limit') }}" required>
							</td>
						</tr>
						<tr>
							<td class="table-form-label">{{ __('adavai.age.restrictions') }}:</td>
							<td  class="form-group">
								<label class="checkbox float-left mt-1">
			                        <input type="checkbox" name="check_age" value="1">
			                        <span class="checkmark"></span>
			                    </label>
			                    <div class="clearfix"></div>
							</td>
						</tr>
						<tr>
							<td class="table-form-label">{{ __('adavai.description') }}:</td>
							<td  class="form-group">
						        <textarea type="text" class="form-control" name="content">{{ old('content') }}</textarea>
							</td>
						</tr>
						<tr>
							<td class="table-form-label"></td>
							<td>
								<button type="submit" class="btn-default w-auto">{{ __('adavai.add.fancy') }}</button>
							</td>
						</tr>
					</table> 
			  		</form>
		  		</div>
		  	</div>

		  </div>
@endsection

resources/views/site/adavai/edit.blade.php
@extends('layouts.main')

@section('title')
	{{ __('adavai.edit') }}
@endsection
<!--@todo translate-->
@section('content') 

		  <div class="col-md-8 px-5 py-1 profile-block">
		  	
		  	<h4 class="page-top-title my-3">{{ __('adavai.edit') }}</h4>

		  	@include('common.alerts')
		  	
		  	<div class="col-12 block-white px-md-5 px-3 py-4 text-left">
		  		<div class="col-md-8 col-12">
			  		<form action="{{ route('adavai.update', $note->id) }}" class="table-form" method="post">
			  			@csrf
			  			@method('PUT')
			  		<table class="table table-sm table-borderless">
						<tr>
							<td class="table-form-label">{{ __('adavai.subject') }}:</td>
							<td class="form-group">
						        <select class="form-control" name="category_id" required>
									@if($categories->count() > 0)
										@foreach($categories as $cat)
											<option value="{{ $cat->id }}" 
												{{ $note->adavai->category_id == $cat->id ? 'selected' : '' }}
												>{{ $cat->title }}</option>
										@endforeach
									@endif
								</select>
							</td>
						</tr>
						<tr>
							<td class="table-form-label">{{ __('adavai.city') }}:</td>
							<td  class="form-group">
						        <select class="form-control" name="city_id">
									@if($countries->count() > 0)
										@foreach($countries as $country)
										<optgroup label="{{ $country->title }}"></optgroup>
											@if($country->cities->count() > 0)
												@foreach($country->cities as $city)
													<option value="{{ $city->id }}" {{ ($note->adavai->city_id == $city->id) ? 'selected' : '' }}>{{ $city->title }}</option>
												@endforeach
											@endif
										@endforeach
									@endif
								</select>
							</td>
						</tr>
						<tr>
							<td class="table-form-label">{{ __('adavai.date') }}:</td>
							<td  class="form-group">
								<input type="datetime-local" name="date" class="form-control" value="{{ $note->adavai->date_for_input }}" required>
							</td>
						</tr>
						<tr>
							<td class="table-form-label">{{ __('adavai.participants.amount') }}:</td>
							<td  class="form-group">
								<input type="number" name="limit" class="form-control" min="1" value="{{ $note->adavai->limit }}" required>
							</td>
						</tr>
						<tr>
							<td class="table-form-label">{{ __('adavai.age.restrictions') }}:</td>
							<td  class="form-group">
								<label class="checkbox float-left mt-1">
			                        <input type="checkbox" name="check_age" value="1" {{ $note->adavai->check_age ? 'checked' : '' }}>
			                        <span class="checkmark"></span>
			                    </label>
			                    <div class="clearfix"></div>
							</td>
						</tr>
						<tr>
							<td class="table-form-label">{{ __('adavai.description') }}:</td>
							<td  class="form-group">
						        <textarea type="text" class="form-control" name="content">{{$note->content}}</textarea>
							</td>
						</tr>
						<tr>
							<td class="table-form-label"></td>
							<td>
								<button type="submit" class="btn-default w-auto">{{ __('adavai.add.fancy') }}</button>
							</td>
						</tr>
					</table> 
			  		</form>
		  		</div>
		  	</div>

		  </div>
@endsection

resources/views/site/adavai/list.blade.php
 @extends('layouts.main')

@section('title')
  Адавай
@endsection

@section('content')

<div class="col-md-8 px-5 py-1 mb-3">
	
		<div class="col-12">
			<div class="row">
				
			<h4 class="col-8 page-top-title p-0 my-3 float-left">{{ __('adavai.fancy') }}</h4>
				<div class="col-4 my-3 p-0 d-md-none d-block">
					<a href="{{ route('adavai.profile') }}" class="btn-default btn-default-sm mb-1">
					{{ __('adavai.organizer') }}</a>
				</div>
			</div>
		</div>

	<div class="clearfix"></div>

	@include('common.alerts')

	<div class="col-12 block-white text-left p-4 mb-4">
		{!! __('adavai.text') !!}
	</div>


	<adavai-notes :owner="0" 
	 			  :user="{{ Auth::user()->id }}" 
	 			  :user_city_id="{{ Auth::user()->city ?? 0 }}" 
	 			  :type="'adavai'" 
		 		  :admin="{{ (Auth::user()->isAdmin() == true) ? 1 : 0 }}"
		 		  :adavai_profile="{{ 0 }}">
	</adavai-notes>



</div>

<div class="col-md-2 block-white-lite p-0 d-md-block d-none">
	<div class="sticky-top side-menu p-4" dir="rtl">
	<div dir="ltr">
		
		<div class="col-12 mb-2 adavai-switch">
			<a href="{{ route('adavai.profile') }}" class="float-left color-black">{{ __('adavai.organizer') }}</a>
			<a href="{{ route('adavai.list') }}" class="float-right color-black active">{{ __('adavai.participant') }}</a>
			<div class="clearfix"></div>
		</div>

	  	<h6 class="font-light ">{{ __('adavai.current.adavais') }}</h6>
	  	<hr>

	  	@if($activeAdavai->count() > 0)
		  	@foreach($activeAdavai as $note)
			  	<div class="mt-3">
			  		<p class="mb-1"><a href="{{ route('adavai.list', ['note' => $note->id]) }}" class="color-black">{{ $note->content_short }}</a></p>
			  		<span class="color-green mr-3">
		        		<i class="far fa-star color-gray"></i> 
		        		<span class="note-action-badge">
		      				{{ $note->likes->count() }}
		    			</span>
		    		</span> 
		    		<span class="color-green mr-3">
		    			<i class="far fa-comment-alt"></i> 
		    			<span class="note-action-badge">
		    				{{ $note->comments->count() }}
		    			</span>
		    		</span>
		    		<span class="color-green ">
		    			<i class="fas fa-user"></i>
		    			<span class="note-action-badge">
		      				{{ $note->adavaiki->count() }}
		    			</span> 
		    		</span> 
			  	</div>
			  	<div>
					<small class="color-gray">{{ $note->adavai->city->country->title }}, {{ $note->adavai->city->title }}</small><br>
					<small class="color-gray">{{ $note->adavai->date_formatted }}</small>
				</div>
				<div>
					<a href="{{ route('adavai.reports', $note->id) }}" class="btn-default btn-default-sm mb-1 mt-1">{{ __('mission.photo.reports') }}</a>
					<a href="{{ route('adavai.leave', $note->id) }}" class="btn-default btn-default-sm mb-1">{{ __('adavai.refuse') }}</a>
					
				</div>
			@endforeach
		@endif

		<h6 class="font-light mt-3">{{ __('adavai.finished.adavais') }}</h6>
	  	<hr>

	  	@if($inactiveAdavai->count() > 0)
		  	@foreach($inactiveAdavai as $note)
			  	<div class="mt-3">
			  		<p class="mb-1"><a href="{{ route('adavai.list', ['note' => $note->id]) }}" class="color-black">{{ $note->content_short }}</a></p>
			  		<span class="color-green mr-3">
		        		<i class="far fa-star color-gray"></i> 
		        		<span class="note-action-badge">
		      				{{ $note->likes->count() }}
		    			</span>
		    		</span> 
		    		<span class="color-green mr-3">
		    			<i class="far fa-comment-alt"></i> 
		    			<span class="note-action-badge">
		    				{{ $note->comments->count() }}
		    			</span>
		    		</span>
		    		<span class="color-green ">
		    			<i class="fas fa-user"></i>
		    			<span class="note-action-badge">
		      				{{ $note->adavaiki->count() }}
		    			</span> 
		    		</span>
			  	</div>
			  	<div>
					<small class="color-gray">{{ $note->adavai->city->country->title }}, {{ $note->adavai->city->title }}</small><br>
					<small class="color-gray">{{ $note->adavai->date_formatted }}</small>
				</div>
				<div>
					<a href="{{ route('adavai.reports', $note->id) }}" target="_blank" class="btn-default btn-default-sm mb-1 mt-1">{{ __('mission.photo.reports') }}</a> 
					<a href="{{ route('adavai.leave', $note->id) }}" class="btn-default btn-default-sm mb-1">{{ __('adavai.delete') }}</a>
				</div>
			@endforeach
		@endif
	</div>
	</div>
</div>

@endsection

resources/views/site/adavai/photo-reports.blade.php
@extends('layouts.main')

@section('title')
  @lang('adavai.fancies') > @lang('mission.photo.reports')
@endsection

@section('content')
		  <div class="col-md-8 px-md-5 px-3 py-1 profile-block">
		  	<h4 class="page-top-title my-3">@lang('adavai.fancies') > @lang('mission.photo.reports')</h4>

			<photo-report 
						:owner="{{ $note->id }}" 
						:user="{{ Auth::user()->id }}" 
						:type="'adavai-report'"
						:user_joined="{{ Auth::user()->id == $note->author_id ? 1 : 0 }}"
						:admin="{{ (Auth::user()->isAdmin() == true) ? 1 : 0 }}">
			</photo-report>
			
		  </div>



@endsection 

resources/views/site/adavai/subscribers.blade.php
 @extends('layouts.main')

@section('title') 
  @lang('adavai.participants.list')
@endsection
@section('content') 
<!--@todo translate-->

<div class="col-md-8 px-5 py-1 mb-3">
	
	<h4 class="col-12 page-top-title my-3">@lang('adavai.participants.list')</h4>
	
	<div class="col-12">
		@include('common.alerts')
	</div>
	
	<div class="col-12">
		<div class="row"> 
			@if($users->count() > 0)
				@foreach($users as $user)
					<div class="col-md-4 mb-4">
						<div class="col-12 block-white user-list-item text-center p-3">
						
						<img src="{{ Croppa::url('public/img/users/'.$user->avatar(), 120, 120) }}" class="rounded-circle">
						<p class="h5 mb-0 mt-1">
							<a href="{{ route('userProfile', $user->nickname) }}" class="profile-name-link" data-toggle="tooltip" data-html="true" title="{{ $user->short_info }}">{{ $user->nickname }}</a>
						</p> 
						<p class="profile-rating mt-1 mb-2">
							<div class="star-rating-readonly" data-rating="{{ $user->rating }}"></div>
						</p>
						
						</div>
					</div>
				@endforeach
			@endif
		</div>
	</div>
</div>

@endsection

resources/views/site/adavai/user-photo-reports.blade.php
@extends('layouts.main')

@section('title')
  @lang('adavai.fancies') > @lang('adavai.organizer.photo.reports')
@endsection

@section('content')
			<!--@todo translate-->
		  <div class="col-md-8 px-md-5 px-3 py-1 profile-block">
		  	<h4 class="page-top-title my-3">@lang('adavai.fancies') > @lang('adavai.organizer.photo.reports')</h4>

			<photo-report  
						:owner="{{ Auth::user()->id }}" 
						:user="{{ Auth::user()->id }}" 
						:type="'user'"
						:author_id="{{ $user->id }}"
						:admin="{{ (Auth::user()->isAdmin() == true) ? 1 : 0 }}">
			</photo-report>
			
		  </div>

@endsection