routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('register/{ref?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
 
Auth::routes(['verify' => true]); 
Route::get('/', 'HomeController@index')->name('home');

Route::get('/app/ask', 'HomeController@getAsk')->name('app.ask.get');
Route::post('/app/ask', 'HomeController@postAsk')->name('app.ask.post');
Route::get('/radio/list', 'HomeController@radio')->name('radio');


App\Http\Controllers\UserController::routes();
App\Http\Controllers\NoteController::routes();
App\Http\Controllers\NoteCommentController::routes();
App\Http\Controllers\UloginController::routes();
App\Http\Controllers\CheckUserDataController::routes();

//mission
App\Http\Controllers\Mission\MissionController::routes();

//group
App\Http\Controllers\GroupController::routes();

//complice
App\Http\Controllers\CompliceController::routes();

//accomplice
App\Http\Controllers\AccompliceController::routes();

//photo-report
App\Http\Controllers\PhotoReportController::routes();

//adavai
App\Http\Controllers\AdavaiController::routes();

//terminated
App\Http\Controllers\TerminatedController::routes();

//diary
App\Http\Controllers\DiaryController::routes();

//notification
App\Http\Controllers\NotificationController::routes();

//product
App\Http\Controllers\ProductController::routes();

//chat
App\Http\Controllers\ChatController::routes();
 
//private-chat
App\Http\Controllers\PrivateChatController::routes();

//admin
App\Http\Controllers\AdminController::routes();

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\LocaleHelper;
use Date;
use App;

class Order extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array 
     */
    protected $fillable = [
        'user_id',
        'product_id'
    ]; 

    public function product()
    {
        return $this->belongsTo('App\Models\Product', 'product_id', 'id');
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id', 'id');
    }

    /**
     * created at.
     *
     * @return date
     */
    public function getOrderDateAttribute()
    { 
        Date::setlocale(App::getLocale());
        return Date::parse($this->attributes['created_at'])
                        ->setTimezone(LocaleHelper::userTimeZone())
                        ->format('j F Y H:i');
    }


}
 

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;
use Croppa;

class Product extends Model
{
	public $defaultAvatar = 'default.png';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'price',
        'price_star',
        'img'
    ];

    /**
     * Avatar
     *
     * @return string 
     */
    public function avatar()
    {
        if ($this->img != '' && !is_null($this->img)) {
            if (Storage::disk('site')->exists('img/products/' . $this->img)) {
                return $this->img;
            } else {
                return $this->defaultAvatar;
            }
        }
        return $this->defaultAvatar;
    }

    /**
     * Check if Group's avatar exists
     *
     * @return boolean
     */
    public function isAvatarExists()
    {
        return ($this->img != '' && !is_null($this->img) && Storage::disk('site')->exists('img/products/' . $this->img));
    }

    public static function delImg($img)
    {
        if(($img != '' && !is_null($img) && Storage::disk('site')->exists('img/products/' . $img)))
        return Croppa::delete('img/products/'.$img);
    }

    /**
     * Delete relation models
     *
     * @return bool
     */
    public static function boot() {
        parent::boot();

        self::deleting(function($item) {
            self::delImg($item->img);
        });
    }

}
 

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Models\Product;
use App\Models\Order;
use App\Models\Settings;
use Session;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */ 
    public function __construct()
    {
        $this->middleware(['auth', 'check.user.data', 'verified', 'last.seen']);
    }

    /**
     * List of products.
     *
     * @return void
     */ 
    public function list()
    {
    	$products = Product::paginate(8);
    	 
    	return view('site.product.list', [
    		'products' => $products
    	]);
    }

    public function buy($id, Request $request)
    {
        $product = Product::findOrFail($id);
        $type = $request->money ? 'money' : 'balance';
        $productPrice = $request->money ? 'price' : 'price_star';

        if (Auth::user()->{$type} <= $product->{$productPrice}) {
            return redirect()->back()->with(['message' => __('message.'.$type.'.not.enough'), 'alert' => 'alert-danger']);
        }

        if (Order::create(['user_id' => Auth::user()->id, 'product_id' => $product->id])) {
            $newBalance = (Auth::user()->{$type} - $product->{$productPrice});

            Auth::user()->update([
                $type => $newBalance
            ]);

            $settings = Settings::first();
            $settings->order_count = $settings->order_count + 1;
            $settings->update();
        }

        return redirect()->back()->with(['message' => __('message.just.bought', ['product' => $product->title]), 'alert' => 'alert-success']);
    }

    /**
     * List of products.
     *
     * @return void
     */ 
    public function myProducts()
    {
        $orders = Order::where('user_id', Auth::user()->id)->orderBy('id', 'desc')->get();
         
        return view('site.product.my-products', [
            'orders' => $orders
        ]);
    }

    /**
     * Define routes
     *
     * @return void
     */
    public static function routes()
    {
        Route::get('/product/list', 'ProductController@list')->name('product.list');
        Route::get('/product/buy/{id}', 'ProductController@buy')->name('product.buy');
        Route::get('/product/my', 'ProductController@myProducts')->name('product.my');
    }

}
  

resources/views/site/product/list.blade.php
 @extends('layouts.main')

@section('title')
  {{ __('product.shop') }}
@endsection

@section('content')

<div class="col-md-9 px-5 py-1 mb-3">
	

	<div class="col-12 my-3">
		<div class="row">
			<div class="col-6">
				<h4 class="page-top-title">{{ __('product.shop') }}</h4>
			</div>
			<div class="col-6 text-right">
				<span class="d-block mt-3">
					<span>
						{{ Auth::user()->money }} @lang('user.roubles')
					</span>
					
					<span class="ml-2">
						{{ Auth::user()->balance }} <i class="text-warning fas fa-star"></i>
					</span>
				</span>
			</div>
		</div> 
	</div>
	
	<div class="col-12">
		@include('common.alerts')
	</div>
	
	<div class="col-12">
		<div class="row">
 
			@if($products->count() > 0)
				@foreach($products as $product)
					<div class="col-md-3 mb-4">
						<div class="col-12 block-white user-list-item text-center py-3 px-4">
						
							<img src="{{ Croppa::url('/public/img/products/'.$product->avatar(), 120, 120) }}" class="rounded-circle">
							<p class="mb-2 mt-2">
									{{ $product->title }}
								</p>
								<span>
									{{ $product->price }} @lang('user.roubles')
								</span>
								|
								<span>
									{{ $product->price_star }} <i class="text-warning fas fa-star"></i>
								</span>

								<a href="{{ route('product.buy', [$product->id]) }}" class="btn-default btn-default-sm d-block mt-2 product-buy-btn"  data-toggle="modal" data-target="#productBuyModal">
									{{ __('product.buy') }}
								</a>
						</div>
					</div>
				@endforeach
			@endif 

			<div class="col-12 mt-3" id="pagination">
				{{ $products->links() }}
			</div>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="productBuyModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <form action="{{ route('product.buy', 1) }}" method="get" id="product_buy_form">
        	<div class="form-group">
        		<button name="balance" value="1" type="submit" class="btn-default btn-default-sm">@lang('product.spend.stars')</button>
        	</div>
        	<div class="form-group m-0">
        		<button name="money" value="1" type="submit" class="btn-green-lite w-100">@lang('product.spend.money')</button>
        	</div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection
@section('js')
<script type="text/javascript">
	$('.product-buy-btn').click(function(){
		var link = $(this).attr('href');
		$('#product_buy_form').attr('action', link);
	});
</script>
@endsection

resources/views/site/product/my-products.blade.php
 @extends('layouts.main')

@section('title')
  {{ __('product.my.products') }}
@endsection

@section('content')

<div class="col-md-9 px-5 py-1 mb-3">
	

	<div class="col-12 my-3">
		<div class="row">
			<div class="col-6">
				<h4 class="page-top-title">{{ __('product.my.products') }}</h4>
			</div>
			<div class="col-6 text-right">
				<span class="d-block mt-3">
					{{ Auth::user()->balance }} <i class="text-warning fas fa-star"></i>
				</span>
			</div>
		</div> 
	</div>
	
	<div class="col-12">
		@include('common.alerts')
	</div>
	
	<div class="col-12">
		<div class="row">
 
			@if($orders->count() > 0)
				@foreach($orders as $order)
				@if($order->product) 
					<div class="col-md-3 mb-4">
						<div class="col-12 block-white user-list-item text-center py-3 px-4">
						
							<img src="{{ Croppa::url('/public/img/products/'.$order->product->avatar(), 120, 120) }}" class="rounded-circle">
							<p class="mb-2 mt-2">
									{{ $order->product->title }}
								</p>
								<span>{{ $order->product->price }} <i class="text-warning fas fa-star"></i></span>
								<br>
								<span>{{ $order->order_date }}</span>
						</div>
					</div>
				@endif 
				@endforeach
			@endif 
		</div>
	</div>
</div>
@endsection