routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('register/{ref?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
 
Auth::routes(['verify' => true]); 
Route::get('/', 'HomeController@index')->name('home');

Route::get('/app/ask', 'HomeController@getAsk')->name('app.ask.get');
Route::post('/app/ask', 'HomeController@postAsk')->name('app.ask.post');
Route::get('/radio/list', 'HomeController@radio')->name('radio');


App\Http\Controllers\UserController::routes();
App\Http\Controllers\NoteController::routes();
App\Http\Controllers\NoteCommentController::routes();
App\Http\Controllers\UloginController::routes();
App\Http\Controllers\CheckUserDataController::routes();

//mission
App\Http\Controllers\Mission\MissionController::routes();

//group
App\Http\Controllers\GroupController::routes();

//complice
App\Http\Controllers\CompliceController::routes();

//accomplice
App\Http\Controllers\AccompliceController::routes();

//photo-report
App\Http\Controllers\PhotoReportController::routes();

//adavai
App\Http\Controllers\AdavaiController::routes();

//terminated
App\Http\Controllers\TerminatedController::routes();

//diary
App\Http\Controllers\DiaryController::routes();

//notification
App\Http\Controllers\NotificationController::routes();

//product
App\Http\Controllers\ProductController::routes();

//chat
App\Http\Controllers\ChatController::routes();
 
//private-chat
App\Http\Controllers\PrivateChatController::routes();

//admin
App\Http\Controllers\AdminController::routes();

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App;

class City extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [ 
        'title',    
        'country_id'    
    ];
    
    /**
     * Relation to country
     *
     * @return relation
     */
    public function country()
    {
        return $this->belongsTo('App\Country', 'country_id');
    }

    /**
     * Get title attribute
     *
     * @return string
     */
    public function getTitleOriginalAttribute()
    {
        return $this->attributes["title"];
    }

    /**
     * Mutate title attribute. Translate
     *
     * @return string
     */
    public function getTitleAttribute($value)
    {
        $arr = explode('/', $value);
        if (count($arr) < 2) return $value;
        $locale = App::getLocale();
        if($locale == 'ru') return $arr[0];
        else return $arr[1];
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route; 
use App\Http\Requests\SettingsRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Cache;
use Croppa;
use Cookie;
use App\Country; 
use App\User;
use App;
use App\Helpers\RobokassaHelper;

class UserController extends Controller
{

    /**
     * Create a new controller instance. 
     *
     * @return void
     */ 
    public function __construct()
    {  
        $this->middleware(['auth', 'check.user.data', 'verified', 'last.seen']);
    }


    /**
     * Show the settings page.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function getSettings()
    {
        $countries = Country::all();
    	return view('site.user.settings', [
            'countries' => $countries
        ]);
    } 

    /**
     * Update user settings
     *
     * @return redirect
     */  
    public function postSettingsUpdate(SettingsRequest $request)
    {
        if (!is_null($request->password)) {
            $request->merge(['password' => Hash::make($request->password)]);
        } else {
            $request->request->remove('password');
        } 

        $update = User::find(Auth::user()->id)->update($request->only([
            "name",
            "gender",
            "born",
            "city",
            "skype",
            "locale",
            "timezone",
            "info",
            "quote",
            "password",
        ]));

        if (in_array($request->locale, ['en', 'ru'])) {
            Cookie::queue(Cookie::forever('locale', $request->locale));  
        }

        if ($request->timezone) Cookie::queue(Cookie::forever('userTimeZoneFromSettings', $request->timezone));

        if ($update) {
            return redirect()->back();  
        }
    }
 
    /**
     * Show user profile
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function getProfile($nickname)
    {
        $user = User::where(['nickname' => $nickname])->firstOrFail();
        $missions = $user->missions()->where('status', 'active')->get();

        if ($user->isOwnProfile()) {  
            return view('site.user.my-profile', [
                'missions' => $missions
            ]);
        } else {
            return view('site.user.profile', [
                'user' => $user,
                'missions' => $missions,
                'markedUser' => Auth::user()->markedUsers()->where([
                    'marked_user_id' => $user->id
                ])->first()
            ]);
        
        } 

    }

   /**
     * Define routes
     *
     * @return void
     */
    public function postAvatarUpload(Request $request)
    {
        
        $request->validate([
            'avatar' => 'required|file|mimes:jpeg,jpg,png,JPEG',
        ]);

        $newFileName = md5(time()).'.'
                           .$request->avatar->getClientOriginalExtension();

        Storage::disk('site')->put('img/users/'.$newFileName, File::get($request->avatar));

        \App\User::find(Auth::user()->id)->update(['img' => $newFileName]);
        return json_encode([
                'status' => 1,
                'message' => __('message.error.occured'),
                'link' => url('/'),
                'callbackFunction' => false
            ], JSON_UNESCAPED_UNICODE);
    }

    /**
     * Delete avatar
     *
     * @return redirect
     */
    public function getAvatarDelete()
    {
        if (Auth::user()->isAvatarExists()) {
            Croppa::delete('img/users/'.Auth::user()->img);
        }

        \App\User::find(Auth::user()->id)->update(['img' => null]);
        return redirect()->back();
    }

    /**
     * Delete profile
     *
     * @return redirect
     */
    public function getProfileDelete()
    {
        return view('site.user.profile-delete');
    }

    /**
     * Delete profile
     *
     * @return redirect
     */
    public function postProfileDelete()
    {
        Auth::user()->update(['freezed' => 1]);
        return redirect()->back();
    }

    /**
     * Mark the given user
     *
     * @return redirect
     */
    public function markUser(Request $request)
    {
        $user = User::findOrFail($request->id);
        $alreadyExists = Auth::user()->markedUsers()->where([
                                        'marked_user_id' => $request->id,
                                        'mission_id' => $request->mission_id
                                    ])->first();

        if ($alreadyExists || Auth::user()->id == $request->id) return redirect()->back();
        
        Auth::user()->markedUsers()->create([
            'mission_id' => $request->mission_id,
            'marked_user_id' => $request->id
        ]);

        return redirect()->back();
    }

    /**
     * Unmark the given user
     *
     * @return redirect
     */
    public function unmarkUser(Request $request)
    {
        $user = User::findOrFail($request->id);
        $marked = Auth::user()->markedUsers()->where([
                            'mission_id' => $request->mission_id,
                            'marked_user_id' => $user->id
                        ])->first();

        if (!$marked || Auth::user()->id == $request->id) return redirect()->back();
        
        $marked->delete();

        return redirect()->back();
    } 

    public function getReplenishBalance()
    {
        return view('site.user.balance-replenish', [
            'user' => Auth::user(),
        ]);
    }

    public function postReplenishBalance(Request $request)
    {
        $user = Auth::user();
        $mrhLogin = RobokassaHelper::getLogin($request->getHttpHost());
        $mrhPass1 = RobokassaHelper::getPassword($request->getHttpHost());
        $isTest = RobokassaHelper::getTestMode($request->getHttpHost());
        $invId = 678678;
        $sum = $request->sum;
        $invDesc = "Пополнение баланса";
        $crc = md5("$mrhLogin:$sum:$invId:$mrhPass1:Shp_user_id=$user->id");
        $link = "https://auth.robokassa.ru/Merchant/Index.aspx?MerchantLogin=$mrhLogin&OutSum=$sum&InvoiceID=$invId&Description=$invDesc&SignatureValue=$crc&Culture=$user->locale&IsTest=$isTest&Shp_user_id=$user->id";
        
        return redirect($link);
    }

    public function replenishStatus($status)
    {
        $message = $status == 'success' ? __('user.balance.resplenish.success') : __('message.smth.went.wrong');
        return view('site.user.replenish-status', [
            'message' => $message,
            'status' => $status
        ]);
    }

    /**
     * Define routes
     *
     * @return void
     */
    public static function routes()
    {
		Route::get('/settings', 'UserController@getSettings')->name('settings');
        Route::post('/settings/update', 'UserController@postSettingsUpdate')->name('settingsUpdate');
        Route::get('/{nickname}', 'UserController@getProfile')->name('userProfile');
        Route::post('/avatar/upload', 'UserController@postAvatarUpload')->name('postAvatarUpload');
        Route::get('/avatar/delete', 'UserController@getAvatarDelete')->name('getAvatarDelete');
        Route::get('/profile/delete', 'UserController@getProfileDelete')->name('profile.delete.get');
        Route::post('/profile/delete', 'UserController@postProfileDelete')->name('profile.delete.post');
        Route::post('/user/mark', 'UserController@markUser')->name('user.mark');
        Route::post('/user/unmark', 'UserController@unmarkUser')->name('user.unmark');
        Route::get('/user/balance/replenish', 'UserController@getReplenishBalance')->name('get.replenish.balance');
        Route::post('/user/balance/replenish', 'UserController@postReplenishBalance')->name('post.replenish.balance');
        Route::get('/user/balance/replenish/{status}', 'UserController@replenishStatus')->name('replenish.status');
    }
}

resources/views/admin/user/add.blade.php
@extends('layouts.admin')

@section('title')
  Добавить страну
@endsection

@section('content')

		  <div class="col-md-8 px-5 py-1 profile-block">
		  	
		  	<h4 class="page-top-title my-3">Добавить</h4>
		  	
		  	<div class="col-12 block-white px-md-5 px-3 py-4 text-left">
		  		<div class="col-md-8 col-12">
			  		<form action="{{ route('admin.country.add.post') }}" class="table-form" method="post">
			  			@csrf
			  		<table class="table table-sm table-borderless">
						<tr>
							<td class="table-form-label">Название:</td>
							<td class="form-group">
						        <input id="title" type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}" required>

						        @if ($errors->has('title'))
						            <span class="invalid-feedback" role="alert">
						                <span>{{ $errors->first('title') }}</span>
						            </span>
						        @endif
							</td>
						</tr>
						<tr>
							<td class="table-form-label"></td>
							<td>
								<button type="submit" class="btn-default btn-default-sm w-auto mt-3">Отправить</button>
							</td>
						</tr>
					</table>
			  		</form>
		  		</div>
		  	</div>

		  </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('title')
  Редактировать пользователя
@endsection

@section('content')

		  <div class="col-md-8 px-5 py-1 profile-block">
		  	
		  	<h4 class="page-top-title my-3">Редактировать</h4>
		  	
		  	<div class="col-12 block-white px-md-5 px-3 py-4 text-left">
		  		<div class="row">
		  		<div class="col-md-8 col-12">

			  		<form action="{{ route('admin.user.edit.post', [$user->id]) }}" class="table-form" method="post">
			  			@csrf
			  		<table class="table table-sm table-borderless">
						<tr>
							<td class="table-form-label">Псевдоним:</td>
							<td class="form-group">
						        <input type="text" class="form-control" value="{{ $user->nickname }}" readonly="true">
							</td>
						</tr>
						<tr>
							<td class="table-form-label">ФИО:</td>
							<td class="form-group">
						        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $user->name }}">

						        @if ($errors->has('name'))
						            <span class="invalid-feedback" role="alert">
						                <span>{{ $errors->first('name') }}</span>
						            </span>
						        @endif
							</td>
						</tr>
						<tr>
							<td class="table-form-label">Email:</td>
							<td class="form-group">
						        <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ $user->email }}">

						        @if ($errors->has('email'))
						            <span class="invalid-feedback" role="alert">
						                <span>{{ $errors->first('email') }}</span>
						            </span>
						        @endif
							</td>
						</tr>
						<tr>
							<td class="table-form-label">Пол:</td>
							<td  class="form-group">
								<select name="gender" id="gender" class="form-control{{ $errors->has('nickname') ? ' is-invalid' : '' }}">
									<option value="">Не выбран</option>
									<option value="male" {{ ($user->gender == 'male' ? 'selected' : '') }}>Мужской</option>
									<option value="female" {{ ($user->gender == 'female' ? 'selected' : '') }}>Женский</option>
								</select>

								@if ($errors->has('gender'))
						            <span class="invalid-feedback" role="alert">
						                <span>{{ $errors->first('gender') }}</span>
						            </span>
						        @endif
							</td>
						</tr>
						<tr>
							<td class="table-form-label">Дата рождения:</td>
							<td  class="form-group">
								<input type="date" name="born" id="born" class="form-control{{ $errors->has('nickname') ? ' is-invalid' : '' }}" value="{{ Date::parse($user->born)->format('Y-m-d') }}"> 
								@if ($errors->has('born'))
						            <span class="invalid-feedback" role="alert">
						                <span>{{ $errors->first('born') }}</span>
						            </span>
						        @endif
							</td>
						</tr>
						<tr>
							<td class="table-form-label">Город:</td>
							<td  class="form-group">
						        <select class="form-control" name="city">
									@if($countries->count() > 0)
										@foreach($countries as $country)
										<optgroup label="{{ $country->title_original }}"></optgroup>
											@if($country->cities->count() > 0)
												@foreach($country->cities as $city)
													<option value="{{ $city->id }}" {{ ($user->city == $city->id) ? 'selected' : '' }}>{{ $city->title_original }}</option>
												@endforeach
											@endif
										@endforeach
									@endif
								</select>

						        @if ($errors->has('city'))
						            <span class="invalid-feedback" role="alert">
						                <span>{{ $errors->first('city') }}</span>
						            </span>
						        @endif
							</td>
						</tr>
						<tr>
							<td class="table-form-label">Skype:</td>
							<td  class="form-group">
								<input type="text" name="skype" id="skype" class="form-control{{ $errors->has('nickname') ? ' is-invalid' : '' }}" value="{{ $user->skype }}"> 
								@if ($errors->has('skype'))
						            <span class="invalid-feedback" role="alert">
						                <span>{{ $errors->first('skype') }}</span>
						            </span>
						        @endif
							</td>
						</tr>
						<tr>
							<td class="table-form-label">Информация:</td>
							<td  class="form-group">
						        <textarea id="info" type="text" class="form-control{{ $errors->has('info') ? ' is-invalid' : '' }}" name="info">{{ $user->info }}</textarea>

						        @if ($errors->has('info'))
						            <span class="invalid-feedback" role="alert">
						                <span>{{ $errors->first('info') }}</span>
						            </span>
						        @endif
							</td> 
						</tr>
						<tr>
							<td class="table-form-label">Статус:</td>
							<td  class="form-group">
						        <textarea id="quote" type="text" class="form-control{{ $errors->has('quote') ? ' is-invalid' : '' }}" name="quote">{{ $user->quote }}</textarea>

						        @if ($errors->has('quote'))
						            <span class="invalid-feedback" role="alert">
						                <span>{{ $errors->first('quote') }}</span>
						            </span>
						        @endif
							</td>
						</tr>
						<tr>
							<td class="table-form-label"></td>
							<td>
								<button type="submit" class="btn-default btn-default-sm w-auto mt-3">Отправить</button>
							</td>
						</tr>
					</table>
			  		</form>
		  		</div>
		  		<div class="col-4">		
	  				<img src="{{ Croppa::url('public/img/users/'.$user->avatar(), 500, 500) }}" class="img-fluid" alt="profile-img">
	  				<br>
	  				<div class="mt-3">
	  					<a href="{{ route('private-chat', [$user->id]) }}" class="btn-default btn-default-sm" target="_blank">Написать пользователю</a>
	  				</div>
	  			</div>
	  			</div>
		  	</div>

		  </div>
@endsection

resources/views/admin/user/index.blade.php
 @extends('layouts.admin')

@section('title')
  Пользователи
@endsection

@section('content')
<div class="col-md-8 px-5 py-1 mb-3">
	
	<div class="col-12 my-3 px-0">
		<div class="row">
			<div class="col-12">
				<h4 class="page-top-title">Пользователи</h4>
			</div>
		</div>
	</div>

 
	@include('common.alerts')

	<div class="col-12 block-white text-left p-4 mb-4">
		<table class="table table-hover fs-10">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Псевдоним</th>
		      <th scope="col">Email</th>
		      <th scope="col">Добавлено</th>
		      <th scope="col"></th>
		      <th scope="col"></th>
		      <th scope="col"></th>
		    </tr>
		  </thead>
		  <tbody>
		  	@if($users)
			  	@foreach($users as $item)
				    <tr>
				      <th scope="row">{{ $loop->index + 1 }}</th>
				      <td>
				      	{{ $item->nickname }}
				      	<br>
				      	@if($item->awards)
		                    @foreach($item->awards as $award)
		                      <small class="badge badge-warning" style="font-weight: 100;"><i class="fas fa-medal"></i> {{ $award->name }}</small>
		                    @endforeach
		                @endif
				      </td>
				      <td>{{ $item->email }}</td>
				      <td>{{ $item->created_at }}</td>
				      <td><a href="{{ route('admin.user.edit.get', [$item->id]) }}" class="color-gray"><i class="fas fa-edit"></i></a></td>
				      <td>
				      	<a href="{{ route('admin.user.delete.get', [$item->id]) }}" class="color-gray confirm-required">
				      		<i class="fas fa-trash"></i>
				      	</a>
				      </td>
				      <td>
					    <div class="dropdown note-options">
	                    <button class="btn btn-link px-1 py-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	                      <i class="fas fa-ellipsis-h"></i>
	                    </button> 
		                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
		                      <a class="dropdown-item confirm-required" href="{{ route('admin.adavai.award.get', [$item->id, 'lucky_manager']) }}">Счастливчик года</a>
		                    </div>
	                    </div>
                	</td>
				    </tr>
			    @endforeach
		    @endif
		  </tbody>
		</table>
	</div>
		<div id="pagination">
			
		  {{ $users->links() }}
		</div>





</div>
@endsection 